//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjAula
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_aula
    {
        public int Id { get; set; }
        public string nomedisciplina { get; set; }
        public Nullable<int> qtd_alunos { get; set; }
        public string nomeprofessor { get; set; }
        public string nomefaculdade { get; set; }
    }
}
